apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-mysql
  template:
    metadata:
      labels:
        app: springboot-mysql
    spec:
      containers:
      - name: springboot-mysql
        image: techcloudifyme/springboot-mysql:v1
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: Admin#123
        - name: MYSQL_HOST
          value: 10.100.206.18
